Update xbash_profile-template, math_lib.sh, os_lib.sh, install.sh, and bashrc-section-template.sh

diff --git a/xbashrc b/xbashrc
--- a/xbashrc
+++ b/xbashrc
@@ -12,26 +12,48 @@ valid_bash_var_name() {
 }
 
 ensure_env_file_exists() {
-    if [ -z "$ENV_FILE" ]; then
+    env_file=${1:-$ENV_FILE}
+
+    if [ -z "$env_file" ]; then
         log_error "Environment file path is not set."
         return 1
     fi
 
-    sudo touch "$ENV_FILE"
-    sudo chown "$XB_USER:$XB_USERGROUP" "$ENV_FILE"
-    # Ensure the .env file is only writable by the owner but readable by everyone
-    sudo chmod 640 "$ENV_FILE"
+    if [ ! -f "$env_file" ]; then
+        sudo touch "$env_file"
+    fi
 
-    if [ -f "$ENV_FILE" ]; then
-        if [ ! -r "$ENV_FILE" ]; then
+    # Ensure the owner of the .env file is $XB_USER
+    if [ "$(stat -f %Su "$env_file")" != "$XB_USER" ]; then
+        sudo chown "$XB_USER:$XB_USERGROUP" "$env_file"
+    fi
+
+    # Ensure the .env file is only writable by the owner but readable by everyone
+    if [ "$(stat -f %A "$env_file")" != "640" ]; then
+        sudo chmod 640 "$env_file"
+    fi
+
+    if [ -f "$env_file" ]; then
+        if [ ! -r "$env_file" ]; then
             log_error "Environment file is not readable."
             return 1
         fi
-        if [ ! -w "$ENV_FILE" ]; then
+        if [ ! -w "$env_file" ]; then
             log_error "Environment file is not writable."
             return 1
         fi
-        if [ ! -s "$ENV_FILE" ]; then
+
+        local env_file_empty="false"
+        #check if contents of the file are exactly the same as the template
+        if [ -s "$env_file" ]; then
+            local template_contents=$(cat "$XB_HOME/xbash_profile-template")
+            local env_file_contents=$(cat "$env_file")
+            if [ "$template_contents" == "$env_file_contents" ]; then
+                env_file_empty="true"
+            fi
+        fi
+
+        if [ ! -s "$env_file" ] || [ "$env_file_empty" == "true" ]; then
             log_state "Environment file is empty. Writing initial values."
             set_env_var "XB_HOME" "$XB_HOME"
             set_env_var "INFRA_DIR" "$INFRA_DIR"
@@ -57,40 +79,42 @@ escape_value() {
 update_env_file() {
     local var_name="$1"
     local value="$2"
+    local env_file=${3:-$ENV_FILE}
     local valid_var_name=$(valid_bash_var_name "$var_name")
     local escaped_value=$(escape_value "$value")
 
-    if [ -z "$ENV_FILE" ]; then
-        log_error "Environment file path is not set."
+    if [ -z "$env_file" ]; then
+        log_error "Environment file path is not set." 2>/dev/null
         return 1
     fi
 
-    if [ ! -f "$ENV_FILE" ]; then
+    if [ ! -f "$env_file" ]; then
         log_error "Environment file does not exist."
         return 1
-    elif [ ! -w "$ENV_FILE" ]; then
+    elif [ ! -w "$env_file" ]; then
         log_error "Environment file is not writable."
         return 1
     fi
 
     # Check if the variable already exists and replace or append accordingly
-    if grep -q "^export $valid_var_name=" "$ENV_FILE"; then
+    if grep -q "^export $valid_var_name=" "$env_file"; then
         # Variable exists, replace its value
-        sed -i '' "s|^export $valid_var_name=.*|export $valid_var_name=$escaped_value|" "$ENV_FILE"
+        sed -i '' "s|^export $valid_var_name=.*|export $valid_var_name=$escaped_value|" "$env_file"
     else
         # Variable does not exist, append to file
-        echo "export $valid_var_name=$escaped_value" >> "$ENV_FILE"
+        echo "export $valid_var_name=$escaped_value" >>"$env_file"
     fi
 }
 
 load_env_file_if_not_set() {
-    if [ -z "$ENV_FILE" ]; then
+    env_file=${1:-$ENV_FILE}
+    if [ -z "$env_file" ]; then
         log_fatal "Environment file path is not set."
         return 1
     fi
 
-    if [ -f "$ENV_FILE" ]; then
-        if [ ! -r "$ENV_FILE" ]; then
+    if [ -f "$env_file" ]; then
+        if [ ! -r "$env_file" ]; then
             log_fatal "Environment file is not readable."
             return 1
         fi
@@ -115,12 +139,13 @@ load_env_file_if_not_set() {
         else
             log_debug "$key is already set to ${!key}"
         fi
-    done < "$ENV_FILE"
+    done <"$env_file"
 }
 
 set_env_var() {
     local var_name="$1"
     local value="$2"
+    local env_file=${3:-$ENV_FILE}
 
     # Check if variable name and value were provided
     if [[ -z "$var_name" || -z "$value" ]]; then
@@ -139,13 +164,73 @@ set_env_var() {
 
     # Export the environment variable
     export "$var_name=$value"
-    log_debug "Set $var_name=$value"
-    update_env_file "$var_name" "$value"
+    log_debug "Set $var_name=$value" 2>/dev/null
+    update_env_file "$var_name" "$value" "$env_file"
+}
+
+get_env_var() {
+    local var_name="$1"
+    local env_file=${2:-$ENV_FILE}
+
+    # Check if variable name was provided
+    if [ -z "$var_name" ]; then
+        log_fatal "Usage: get_env_var <variable_name>"
+        return 1
+    fi
+
+    # Check if the variable is set in the current environment
+    if [ -z "${!var_name}" ]; then
+        # Variable is not set in the current environment
+        log_debug "$var_name is not set in the current environment."
+        # Check if the variable is set in the environment file
+        if grep -q "^export $var_name=" "$env_file"; then
+            # Variable is set in the environment file
+            local value=$(grep "^export $var_name=" "$env_file" | cut -d'=' -f2-)
+            # Remove leading and trailing whitespace
+            value=$(echo "$value" | xargs)
+            log_debug "$var_name is set to $value in the environment file."
+            # Export the variable to the current environment
+            export "$var_name=$value"
+            # Return the value
+            echo "$value"
+        else
+            # Variable is not set in the environment file
+            log_debug "$var_name is not set in the environment file."
+            return 1
+        fi
+    else
+        # Variable is set in the current environment
+        log_debug "$var_name is set to ${!var_name} in the current environment."
+        # Return the value
+        echo "${!var_name}"
+    fi
+}
+
+unset_env_var() {
+    local var_name="$1"
+    local env_file=${2:-$ENV_FILE}
+
+    # Check if variable name was provided
+    if [ -z "$var_name" ]; then
+        log_fatal "Usage: unset_env_var <variable_name>"
+        return 1
+    fi
+
+    # Unset the variable in the current environment
+    unset "$var_name"
+    log_debug "Unset $var_name" 2>/dev/null
+
+    # Remove the variable from the environment file
+    if grep -q "^export $var_name=" "$env_file"; then
+        sed -i '' "/^export $var_name=/d" "$env_file"
+        log_debug "Removed $var_name from $env_file"
+    fi
 }
 
 load_env_file() {
-    if [ -f "$ENV_FILE" ]; then
-        if [ ! -r "$ENV_FILE" ]; then
+    env_file=${1:-$ENV_FILE}
+    if [ -f "$env_file" ]; then
+        if [ ! -r "$env_file" ]; then
             log_fatal "Environment file is not readable."
             return 1
         fi
@@ -154,7 +239,7 @@ load_env_file() {
         return 1
     fi
 
-    source "$ENV_FILE"
+    source "$env_file"
 }
 
 check_all_vars_set_in_env_file() {
@@ -212,7 +297,7 @@ check_all_ip_vars_set_in_env_file_and_reachable() {
             return 1
         fi
 
-        if ! ping -c 1 -W 1 "$ip_address" > /dev/null 2>&1; then
+        if ! ping -c 1 -W 1 "$ip_address" >/dev/null 2>&1; then
             log_error "IP address $ip_address for $var_name is not reachable."
             return 1
         fi
@@ -245,9 +330,9 @@ check_var_set_in_env_file() {
     fi
 }
 
-update_bashrc(){
-    local instantiated_template="$RUN_TEMP_DIR/mf-bashrc-section.sh"
-    cp "$INFRA_DIR/bashrc-section-template.sh" "$instantiated_template"
+update_bashrc() {
+    local instantiated_template="$RUN_WORKSPACE/xb-bashrc-section.sh"
+    cp "$XB_HOME/bashrc-section-template.sh" "$instantiated_template"
     sed -i '' "s|ENV_FILE|$ENV_FILE|g" "$instantiated_template"
     sed -i '' "s|XB_HOME|$XB_HOME|g" "$instantiated_template"
     sed -i '' "s|MG_WORKDIR|$MG_WORKDIR|g" "$instantiated_template"
@@ -261,24 +346,14 @@ update_bashrc(){
     update_file_section "$instantiated_template" "$XB_USER_HOME/.bashrc" "$MG_BASHRC_SECTION_START" "$MG_BASHRC_SECTION_END" "$MG_BASHRC_SECTION_COMMENT"
 }
 
-new(){
-    project_path=$1
-    project_name=$2
+xb_version() {
+    local xb_version_file="$XB_HOME/version.txt"
 
-    if [ -z "$project_path" ]; then
-        echo
-        return
-    fi
-}
-
-mg_version() {
-    local mg_version_file="$XB_HOME/version.txt"
-
-    if [ ! -f "$mg_version_file" ]; then
+    if [ ! -f "$xb_version_file" ]; then
         log_fatal "Version file not found."
     fi
 
-    local result=$(cat "$mg_version_file")
+    local result=$(cat "$xb_version_file")
 
     if [ -z "$result" ]; then
         log_fatal "Version file is empty."
@@ -289,7 +364,9 @@ mg_version() {
 }
 
 source_scripts() {
-    scripts_to_source=("$@")
+    # Convert the space-separated string into an array
+    IFS=' ' read -r -a scripts_to_source <<<"$@"
+
     for script_path in "${scripts_to_source[@]}"; do
         source_script "$script_path"
         # prefix_source "$XB_HOME" "$script_path"
@@ -298,7 +375,6 @@ source_scripts() {
 
 list_directory_contents() {
     local dir_path="$1"
-    local arr_name=$2
 
     # Check if the directory exists
     if [[ ! -d "$dir_path" ]]; then
@@ -306,46 +382,48 @@ list_directory_contents() {
         return 1
     fi
 
-    # Clear the array using indirect expansion
-    eval "$arr_name=()"
+    # Initialize an empty array to store the paths
+    local paths=()
 
     # Populate the array with absolute paths
     local item
     for item in "$dir_path"/*; do
         if [[ -e "$item" ]]; then # Check if the item exists
             # macOS compatible realpath alternative
-            local abs_path="$(cd "$(dirname "$item")"; pwd)/$(basename "$item")"
-            # Append to array indirectly
-            eval "$arr_name+=(\"\$abs_path\")"
+            local abs_path
+            abs_path="$(cd "$(dirname "$item")" && pwd)/$(basename "$item")"
+            # Append to the paths array
+            paths+=("$abs_path")
         fi
     done
+
+    # Echo the paths as a space-separated list
+    echo "${paths[*]}"
+}
+
+to_uppercase() {
+    local input_string="$1"
+    echo "$input_string" | tr '[:lower:]' '[:upper:]'
 }
 
 print_xb_header() {
     # ANSI color codes for styling
-    NC='\033[0m'  # No Color
+    NC='\033[0m' # No Color
     GREEN='\033[0;32m'
     BLUE='\033[0;34m'
     YELLOW='\033[1;33m'
     CYAN='\033[0;36m'
     MAGENTA='\033[0;35m'
 
-    # ┌─┐┬─┐┌─┐┌─┐┌─┐┌┐ ┌─┐┌─┐┬ ┬
-    # │  ├┬┘│ │└─┐└─┐├┴┐├─┤└─┐├─┤
-    # └─┘┴└─└─┘└─┘└─┘└─┘┴ ┴└─┘┴ ┴
-
-    echo -e "${YELLOW}╔═╗╦═╗╔═╗╔═╗╔═╗╔╗ ╔═╗╔═╗╦ ╦${NC}"
-    echo -e "${YELLOW}║  ╠╦╝║ ║╚═╗╚═╗╠╩╗╠═╣╚═╗╠═╣${NC}"
-    echo -e "${YELLOW}╚═╝╩╚═╚═╝╚═╝╚═╝╚═╝╩ ╩╚═╝╩ ╩${MAGENTA}v$(mg_version)${NC}"
+    echo -e "${YELLOW}"
+    print_title "$(to_uppercase "$PROJECT_NAME") crossbash"
+    echo -e "${MAGENTA}xbash v$(xb_version)${NC}"
 
     echo -e "${YELLOW}State file: ${MAGENTA}$RUN_STATE_FILE${NC}"
     echo -e "${YELLOW}Log file: ${MAGENTA}$RUN_LOG_FILE${NC}"
 }
 
-# Prevent the file from being sourced multiple times
-if [ -z "$ROOT_BASH_SOURCED" ]; then
-    ROOT_BASH_SOURCED=1
-
+initialize_xb() {
     source_script() {
         local script_path="$1"
         if [ ! -f "$script_path" ]; then
@@ -355,70 +433,141 @@ if [ -z "$ROOT_BASH_SOURCED" ]; then
         source "$script_path"
     }
 
-    LOG_LEVEL=5
-    ENV_FILE="/etc/machinegenesis/mg_env"
-    sudo mkdir -p "$(dirname "$ENV_FILE")"
-    sudo touch "$ENV_FILE"
-    sudo chmod +x "$ENV_FILE"
+    if [ -z "$XB_HOME" ]; then
+        XB_HOME="/Users/bahram/ws/prj/machinegenesis/crossbash" #"$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
-    INFRA_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-    XB_HOME="$(dirname "$INFRA_DIR")"
+        echo "CROSSBASH home is at:"
+        read -p "[$XB_HOME]: " input
+        XB_HOME=${input:-$XB_HOME}
+        set_env_var "XB_HOME" "$XB_HOME" "$MASTER_ENV_FILE"
+    fi
+    LIB_DIR="$XB_HOME/lib"
 
-    echo "Please enter the home directory for MachineGenesis:"
-    read -p "[$XB_HOME]: " input
-    XB_HOME=${input:-$XB_HOME}
+    if [ -z "$PROJ_HOME_DIR" ]; then
+        PROJ_HOME_DIR="/Users/bahram/ws/prj/machinegenesis"
+        echo "Project home is at:"
+        read -p "[$PROJ_HOME_DIR]: " input
+        PROJ_HOME_DIR=${input:-$PROJ_HOME_DIR}
+        set_env_var "PROJ_HOME_DIR" "$PROJ_HOME_DIR" "$MASTER_ENV_FILE"
+    fi
 
-    source_script "$INFRA_DIR/lib/log_lib.sh"
+    ENV_FILE="$PROJ_HOME_DIR/.xbash_profile"
 
-    ABRCITY_HOME="$XB_HOME/abrcity"
-    MACHINEFABRIC_HOME="$XB_HOME/machinefabric"
-    INFRA_DIR="$XB_HOME/infra"
-    LIB_DIR="$INFRA_DIR/lib"
+    if [ ! -f "$ENV_FILE" ]; then
+        cp "$XB_HOME/xbash_profile-template" "$ENV_FILE" || { echo "Failed to create $ENV_FILE" && exit 1; }
+        sudo chmod +x "$ENV_FILE"
+    fi
 
-    XB_USER=$(whoami)
-    echo "Please enter the user for MachineGenesis"
-    read -p "[$XB_USER]: " input
-    XB_USER=${input:-$XB_USER}
+    source_script "$ENV_FILE" || { echo "Failed to source $ENV_FILE" && exit 1; }
 
-    XB_USERGROUP=$(id -gn "$XB_USER")
-    echo "Please enter the user group for MachineGenesis:"
-    read -p "[$XB_USERGROUP]: " input
-    XB_USERGROUP=${input:-$XB_USERGROUP}
+    # ABRCITY_HOME="$XB_HOME/abrcity"
+    # MACHINEFABRIC_HOME="$XB_HOME/machinefabric"
+    # INFRA_DIR="$XB_HOME/infra"
 
-    XB_USER_HOME=$(eval echo ~$XB_USER)
+    if [ -z "$LOG_LEVEL" ]; then
+        LOG_LEVEL=3
+        set_env_var "LOG_LEVEL" "$LOG_LEVEL"
+    fi
 
-    MG_WORKDIR="$XB_USER_HOME/mg"
+    source_script "$XB_HOME/lib/log_lib.sh" || { echo "Failed to source log_lib.sh" >&2 && exit 1; }
 
-    echo "Please enter the work directory for MachineGenesis:"
-    read -p "[$MG_WORKDIR]: " input
-    MG_WORKDIR=${input:-$MG_WORKDIR}
+    if [ -z "$PROJECT_NAME" ]; then
+        PROJECT_NAME=$(basename "$PROJ_HOME_DIR")
+        echo "Project name is:"
+        read -p "[$PROJECT_NAME]: " input
+        PROJECT_NAME=${input:-$PROJECT_NAME}
+        set_env_var "PROJECT_NAME" "$PROJECT_NAME"
+    fi
 
-    HOST_LAN_ADAPTER="eno2"
+    if [ -z "$SUB_PROJECTS" ]; then
+        defined_sub_projects=$(get_env_var "SUB_PROJECTS")
 
-    echo "Please enter the host LAN adapter:"
-    read -p "[$HOST_LAN_ADAPTER]: " input
-    HOST_LAN_ADAPTER=${input:-$HOST_LAN_ADAPTER}
+        if [ ${#defined_sub_projects[@]} -eq 0 ]; then
+            echo "The xbash profile at your project home directory does not define any sub projects."
+            # echo "Please enter the sub projects paths separated by space:"
+            # read -p "[$entered_subprojects]: " input
+            # entered_subprojects=${input:-$entered_subprojects}
+            # set_env_var "SUB_PROJECTS" "$entered_subprojects"
+        else
+            echo "The xbash profile at your project home directory defines the following sub projects:"
+            echo "$defined_sub_projects"
+            # echo "Do you want to add more sub projects?"
+            # read -p "[y/n]: " input
+            # if [ "$input" == "y" ]; then
+            #     echo "Please enter the sub projects paths separated by space:"
+            #     read -p "[$defined_sub_projects]: " input
+            #     entered_subprojects=${input:-$defined_sub_projects}
+            #     set_env_var "SUB_PROJECTS" "$entered_subprojects"
+            # fi
+        fi
+    fi
 
-    HOST_WLAN_ADAPTER="wlo1"
+    if [ -z "$PROJECT_WORKDIR" ]; then
+        PROJECT_WORKDIR="$USER_XB_DIR/$PROJECT_NAME"
 
-    echo "Please enter the host WLAN adapter:"
-    read -p "[$HOST_WLAN_ADAPTER]: " input
-    HOST_WLAN_ADAPTER=${input:-$HOST_WLAN_ADAPTER}
+        echo "Please enter the working directory for your project:"
+        read -p "[$PROJECT_WORKDIR]: " input
+        PROJECT_WORKDIR=${input:-$PROJECT_WORKDIR}
+        mkdir -p "$PROJECT_WORKDIR"
+        set_env_var "PROJECT_WORKDIR" "$PROJECT_WORKDIR"
 
-    declare -a scripts_to_source
-    list_directory_contents "$LIB_DIR" scripts_to_source
+        set_env_var "CACHE_DIR" "$XB_USER_HOME/.crossbash/cache"
+
+    fi
+
+    if [ -z "$HOST_LAN_ADAPTER" ]; then
+        HOST_LAN_ADAPTER="eno2"
+
+        echo "Please enter the host LAN adapter:"
+        read -p "[$HOST_LAN_ADAPTER]: " input
+        HOST_LAN_ADAPTER=${input:-$HOST_LAN_ADAPTER}
+        set_env_var "HOST_LAN_ADAPTER" "$HOST_LAN_ADAPTER"
+    fi
+
+    if [ -z "$HOST_WLAN_ADAPTER" ]; then
+        HOST_WLAN_ADAPTER="wlo1"
+
+        echo "Please enter the host WLAN adapter:"
+        read -p "[$HOST_WLAN_ADAPTER]: " input
+        HOST_WLAN_ADAPTER=${input:-$HOST_WLAN_ADAPTER}
+        set_env_var "HOST_WLAN_ADAPTER" "$HOST_WLAN_ADAPTER"
+    fi
+
+    scripts_to_source=$(list_directory_contents "$LIB_DIR")
 
     source_scripts "${scripts_to_source[@]}"
 
+    # add_wait_marquee
+
     print_xb_header
-    ensure_env_file_exists
+    ensure_env_file_exists "$ENV_FILE"
     update_bashrc
     install_dependency_repos
     install_dependencies
     manual_setup
+    download_duckdb
+    initialize_db
+
     write_to_run_state "timestamp" "$(date +'%Y-%m-%d %H:%M:%S')"
-    write_to_run_state "mg_version" "$(mg_version)"
+    write_to_run_state "xb_version" "$(xb_version)"
     write_to_run_state "running_user" "$(whoami)"
+    # remove_wait_marquee
+}
+
+# Prevent the file from being sourced multiple times
+if [ -z "$ROOT_BASH_SOURCED" ]; then
+    ROOT_BASH_SOURCED=1
+
+    XB_USER=$(whoami)
+    XB_USER_HOME=$(eval echo ~"$XB_USER")
+    XB_USERGROUP=$(id -gn "$XB_USER")
+    USER_XB_DIR="$XB_USER_HOME/.crossbash"
+    MASTER_ENV_FILE="$USER_XB_DIR/master.env"
+    mkdir -p "$USER_XB_DIR"
+    touch "$MASTER_ENV_FILE"
+    source "$MASTER_ENV_FILE"
+
+    initialize_xb
 fi
 
 if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
@@ -427,12 +576,12 @@ if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
         exit 0
     fi
 
-    func_name="$1"  # Store the first argument (function name)
-    shift           # Remove the first argument, now $@ contains only the arguments for the function
+    func_name="$1" # Store the first argument (function name)
+    shift          # Remove the first argument, now $@ contains only the arguments for the function
 
     # Check if the function exists
-    if declare -f "$func_name" > /dev/null; then
-        "$func_name" "$@"  # Call the function with the remaining arguments
+    if declare -f "$func_name" >/dev/null; then
+        "$func_name" "$@" # Call the function with the remaining arguments
     else
         log_fatal "'$func_name' is not a valid function name."
         exit 1
